"""Provider-neutral, allowlisted, budgeted feed watcher primitives."""

from .execution import (
    SynchronousWatcherExecutor,
    WatcherExecutionResult,
    WatcherStepResult,
)
from .feedsets import (
    FeedSetRegistry,
    FeedSetResolutionError,
    TargetNotAllowedError,
    authorize_target,
)
from .models import (
    AuthorizedTarget,
    BudgetChargeResult,
    BudgetStatus,
    CursorCommitResult,
    CursorCommitStatus,
    CursorState,
    RunFence,
    ScanFeedSetResult,
    ScanStatus,
    ScheduleDecision,
    TargetRequest,
)
from .schedule import ScheduleTimezoneError, evaluate_schedule
from .service import WatcherService
from .store import (
    CREDIT_MICROS_PER_CREDIT,
    MAX_CURSOR_BYTES,
    MAX_CURSOR_SEQUENCE,
    MAX_CURSOR_SEQUENCE_ADVANCE,
    RESERVED_LANE,
    RESERVED_POOL_ALIAS,
    FeedSetLookupError,
    ReservedRouteError,
    StaleRunFenceError,
    SummaryMetadataError,
    WatcherPersistenceError,
    WatcherStore,
    credits_to_micros,
)

__all__ = [
    "CREDIT_MICROS_PER_CREDIT",
    "MAX_CURSOR_BYTES",
    "MAX_CURSOR_SEQUENCE",
    "MAX_CURSOR_SEQUENCE_ADVANCE",
    "RESERVED_LANE",
    "RESERVED_POOL_ALIAS",
    "AuthorizedTarget",
    "BudgetChargeResult",
    "BudgetStatus",
    "CursorCommitResult",
    "CursorCommitStatus",
    "CursorState",
    "FeedSetLookupError",
    "FeedSetRegistry",
    "FeedSetResolutionError",
    "ReservedRouteError",
    "RunFence",
    "ScanFeedSetResult",
    "ScanStatus",
    "ScheduleDecision",
    "ScheduleTimezoneError",
    "StaleRunFenceError",
    "SummaryMetadataError",
    "SynchronousWatcherExecutor",
    "TargetNotAllowedError",
    "TargetRequest",
    "WatcherPersistenceError",
    "WatcherService",
    "WatcherExecutionResult",
    "WatcherStepResult",
    "WatcherStore",
    "authorize_target",
    "credits_to_micros",
    "evaluate_schedule",
]
