"""Typed provider contracts."""

from gatehouse.providers.base import (
    CredentialCustodyKind,
    CredentialRole,
    OperationSpec,
    ProviderErrorClass,
    ProviderRequest,
    ProviderResponse,
    RetrySafety,
    SideEffectClass,
)
from gatehouse.providers.registry import (
    DEFAULT_PROVIDER_REGISTRY,
    FIRECRAWL_DESCRIPTOR,
    FOUNDATION_PROVIDER_IDS,
    AuthenticationStrategy,
    ProviderContractError,
    ProviderDescriptor,
    ProviderImplementationState,
    ProviderOperationPolicy,
    ProviderRegistry,
    QuotaCounterKind,
    QuotaDimensionSpec,
    RequestBodyPolicy,
    ResetWindowKind,
)
from gatehouse.providers.scripted import (
    ScriptedManifestError,
    ScriptedProviderError,
    ScriptedProviderTransport,
    ScriptedResponseExhausted,
)
from gatehouse.providers.transport import (
    HttpxProviderTransport,
    ProviderNetworkDisabledError,
    ProviderPreHandoffError,
    ProviderResponseTooLargeError,
)

__all__ = [
    "CredentialCustodyKind",
    "CredentialRole",
    "OperationSpec",
    "ProviderErrorClass",
    "ProviderRequest",
    "ProviderResponse",
    "RetrySafety",
    "SideEffectClass",
    "HttpxProviderTransport",
    "ProviderNetworkDisabledError",
    "ProviderPreHandoffError",
    "ProviderResponseTooLargeError",
    "ScriptedManifestError",
    "ScriptedProviderError",
    "ScriptedProviderTransport",
    "ScriptedResponseExhausted",
    "AuthenticationStrategy",
    "DEFAULT_PROVIDER_REGISTRY",
    "FIRECRAWL_DESCRIPTOR",
    "FOUNDATION_PROVIDER_IDS",
    "ProviderContractError",
    "ProviderDescriptor",
    "ProviderImplementationState",
    "ProviderOperationPolicy",
    "ProviderRegistry",
    "QuotaCounterKind",
    "QuotaDimensionSpec",
    "RequestBodyPolicy",
    "ResetWindowKind",
]
