"""Crash-safe SQLite persistence primitives for Gatehouse."""

from .audit import AuditBufferFullError, AuditEvent, BoundedAuditWriter
from .connection import (
    DEFAULT_BUSY_TIMEOUT_MS,
    DatabaseConfigurationError,
    DatabaseError,
    IntegrityReport,
    TransactionNestingError,
    connect_database,
    inspect_integrity,
    transaction,
)
from .migrations import (
    MIGRATIONS,
    Migration,
    MigrationDriftError,
    MigrationError,
    MigrationOrderError,
    apply_migrations,
    open_migrated_database,
)
from .quota_state import (
    QuotaObservationResult,
    QuotaObservationStatus,
    QuotaScopeHealthState,
    QuotaStateSource,
    QuotaTransitionResult,
    QuotaTransitionStatus,
    RedactedQuotaScopeStatus,
    SqliteQuotaStateRepository,
    redacted_status_json,
)
from .recovery import AsyncCheckpointRecoveryError, RecoveryReport, recover_startup
from .repository import (
    ApprovalConsumeResult,
    ApprovalConsumeStatus,
    GatehouseRepository,
    LeaseResult,
    LeaseStatus,
    QuotaReservationResult,
    QuotaReservationStatus,
)
from .retention import (
    RetentionPolicy,
    RetentionReport,
    apply_retention,
    checkpoint_wal,
    database_footprint,
)
from .runaway import (
    MAXIMUM_BURST_CONCURRENCY,
    MAXIMUM_BURST_CREDITS,
    MAXIMUM_BURST_DURATION_MS,
    MAXIMUM_BURST_OPERATIONS,
    MAXIMUM_BURST_REQUESTS,
    RunawayAdmission,
    RunawayAdmissionState,
    RunawayBurstPermit,
    RunawayQuarantineActionResult,
    RunawayQuarantineConflict,
    RunawayQuarantineError,
    RunawayQuarantinePersistenceError,
    RunawayQuarantineRecord,
    RunawayQuarantineState,
    SqliteRunawayQuarantineService,
)

__all__ = [
    "ApprovalConsumeResult",
    "ApprovalConsumeStatus",
    "AsyncCheckpointRecoveryError",
    "AuditBufferFullError",
    "AuditEvent",
    "BoundedAuditWriter",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "DatabaseConfigurationError",
    "DatabaseError",
    "GatehouseRepository",
    "IntegrityReport",
    "LeaseResult",
    "LeaseStatus",
    "MAXIMUM_BURST_CONCURRENCY",
    "MAXIMUM_BURST_CREDITS",
    "MAXIMUM_BURST_DURATION_MS",
    "MAXIMUM_BURST_OPERATIONS",
    "MAXIMUM_BURST_REQUESTS",
    "MIGRATIONS",
    "Migration",
    "MigrationDriftError",
    "MigrationError",
    "MigrationOrderError",
    "QuotaReservationResult",
    "QuotaReservationStatus",
    "QuotaObservationResult",
    "QuotaObservationStatus",
    "QuotaScopeHealthState",
    "QuotaStateSource",
    "QuotaTransitionResult",
    "QuotaTransitionStatus",
    "RedactedQuotaScopeStatus",
    "RecoveryReport",
    "RunawayAdmission",
    "RunawayAdmissionState",
    "RunawayBurstPermit",
    "RunawayQuarantineActionResult",
    "RunawayQuarantineConflict",
    "RunawayQuarantineError",
    "RunawayQuarantinePersistenceError",
    "RunawayQuarantineRecord",
    "RunawayQuarantineState",
    "RetentionPolicy",
    "RetentionReport",
    "SqliteQuotaStateRepository",
    "SqliteRunawayQuarantineService",
    "TransactionNestingError",
    "apply_migrations",
    "apply_retention",
    "checkpoint_wal",
    "connect_database",
    "database_footprint",
    "inspect_integrity",
    "open_migrated_database",
    "redacted_status_json",
    "recover_startup",
    "transaction",
]
