"""Administrative authentication and secret-free view contracts."""

from .auth import (
    AdminAuthCapacityExceeded,
    AdminAuthenticationError,
    AdminAuthManager,
    AdminLoginSession,
    AdminPrincipal,
    MintedLoginCode,
)
from .control import (
    CONTROL_CAPABILITY_HEADER,
    ControlAdminLoginCode,
    ControlAuthorityError,
    ControlDaemonStatus,
    ControlDrainResult,
    ControlHealthProbe,
    ControlLaunchAuthority,
    ControlSessionLaunch,
    ControlSessionLaunchRequest,
    ControlSessionMutation,
    LocalControlService,
    create_local_control_router,
)
from .control_capability import (
    ControlCapabilityStorageError,
    ControlCapabilityVerifier,
    load_control_capability,
    load_control_capability_verifier,
    provision_control_capability,
)
from .models import (
    AdminBackend,
    AdminStatus,
    ApprovalActionRequest,
    ApprovalActionResult,
    ApprovalDecision,
    ApprovalView,
    CredentialSummary,
    IncidentSummary,
    PoolSummary,
    ReconciliationSummary,
)
from .persistence import (
    ApprovalDecisionConflict,
    ApprovalPersistenceError,
    SqliteApprovalAdminService,
)

__all__ = [
    "CONTROL_CAPABILITY_HEADER",
    "AdminAuthenticationError",
    "AdminAuthCapacityExceeded",
    "AdminAuthManager",
    "AdminBackend",
    "AdminLoginSession",
    "AdminPrincipal",
    "AdminStatus",
    "ApprovalActionRequest",
    "ApprovalActionResult",
    "ApprovalDecision",
    "ApprovalDecisionConflict",
    "ApprovalPersistenceError",
    "ApprovalView",
    "CredentialSummary",
    "ControlAdminLoginCode",
    "ControlAuthorityError",
    "ControlCapabilityStorageError",
    "ControlCapabilityVerifier",
    "ControlDaemonStatus",
    "ControlDrainResult",
    "ControlHealthProbe",
    "ControlLaunchAuthority",
    "ControlSessionLaunch",
    "ControlSessionLaunchRequest",
    "ControlSessionMutation",
    "IncidentSummary",
    "MintedLoginCode",
    "LocalControlService",
    "PoolSummary",
    "ReconciliationSummary",
    "SqliteApprovalAdminService",
    "create_local_control_router",
    "load_control_capability",
    "load_control_capability_verifier",
    "provision_control_capability",
]
