"""Bounded, session-fair scheduling primitives."""

from .fair import (
    BoundedFairScheduler,
    CancellationResult,
    ClientCapacityLimits,
    DispatchPermit,
    DuplicateRequest,
    PriorityClass,
    QueueCapacityExceeded,
    QueueExpired,
    QueueTicket,
    QuotaScopeSaturated,
    RequestCancelled,
    SchedulerLimits,
    SchedulerSnapshot,
    ServiceLimits,
    UnknownClient,
    UnknownService,
    WorkItem,
)

__all__ = [
    "BoundedFairScheduler",
    "CancellationResult",
    "ClientCapacityLimits",
    "DispatchPermit",
    "DuplicateRequest",
    "PriorityClass",
    "QueueCapacityExceeded",
    "QueueExpired",
    "QueueTicket",
    "QuotaScopeSaturated",
    "RequestCancelled",
    "SchedulerLimits",
    "SchedulerSnapshot",
    "ServiceLimits",
    "UnknownService",
    "UnknownClient",
    "WorkItem",
]
